server:
  port: 8082

spring:
  application:
    name: my-service-c
  cloud:
    config:
      discovery:
        enabled: true
        service-id: my-config-server
    enabled: true
  profiles:
    active: dev
    
# To enable the actuator to see hystrix-stream at http://localhost:8080/actuator/hystrix.stream 
# To make an actuator endpoint available via HTTP, it needs to be both enabled and exposed. By default:
# Only the /health and /info endpoints are exposed, regardless of Spring Security being present and configured in your application.
# All endpoints but /shutdown are enabled.
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
    shutdown:
      enabled: true
    
eureka: #tells about the Eureka server details and its refresh time
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    lease:
      duration: 5
    enabled: true
    # by default service uses service name as id to differentiate each other in other env, but in local sometime they conflict. 
    # So we need to manually give instance id
  instance:
    instance-id: ${spring.application.name}:${random.int}
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2